// Emails the weekly AI marketing report after a successful run. Reuses the
// same Resend setup as the quote/contact mailers (RESEND_API_KEY /
// RESEND_FROM_EMAIL). Recipient comes from AI_REPORT_EMAIL — set on the LIVE
// backend only, so staging runs never email. No images: renders everywhere.

const esc = (s) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const HEALTH_STYLE = {
  good: ["On track", "#e2f6ea", "#1d9e57"],
  warn: ["Needs attention", "#fdf1da", "#b07c14"],
  bad: ["Off track", "#fde3e3", "#c53c3c"],
};
const IMPACT_COLOR = { high: "#1d9e57", medium: "#b07c14", low: "#7a869c" };
const SECTION_TITLES = { website: "Website", seo: "SEO", ads: "Google Ads" };

function chip(label, bg, color) {
  return `<span style="display:inline-block;padding:2px 10px;border-radius:999px;background:${bg};color:${color};font-size:11px;font-weight:700;">${esc(label)}</span>`;
}

function renderSection(s) {
  const [hLabel, hBg, hColor] = HEALTH_STYLE[s.health] || HEALTH_STYLE.warn;
  const findings = (s.findings || [])
    .map((f) => `<li style="margin:0 0 7px;line-height:1.5;">${esc(f)}</li>`)
    .join("");
  const recs = (s.recommendations || [])
    .map((r) => `
      <div style="border-left:3px solid #4a80e0;padding:8px 12px;margin:0 0 10px;background:#f7faff;border-radius:0 8px 8px 0;">
        <div style="font-weight:700;color:#14264d;margin-bottom:2px;">${esc(r.action)}
          <span style="font-weight:400;">&nbsp;${chip(`${r.impact} impact`, "#eef2fa", IMPACT_COLOR[r.impact] || "#7a869c")}
          ${chip(`${r.effort} effort`, "#eef2fa", "#7a869c")}</span></div>
        <div style="font-size:13px;color:#5a6880;line-height:1.5;">${esc(r.why)}</div>
      </div>`)
    .join("");
  return `
    <div style="margin:0 0 22px;padding:18px 20px;background:#ffffff;border:1px solid #e3e9f4;border-radius:12px;">
      <div style="margin:0 0 10px;"><span style="font-size:15px;font-weight:800;color:#14264d;">${esc(SECTION_TITLES[s.key] || s.title || s.key)}</span>
        &nbsp;${chip(hLabel, hBg, hColor)}</div>
      <ul style="margin:0 0 12px;padding-left:20px;font-size:13.5px;color:#33415e;">${findings}</ul>
      ${recs}
    </div>`;
}

export function buildAiReportEmail(meta, parsed, rawText) {
  const when = new Date(meta.createdAt).toLocaleDateString("en-ZA", {
    timeZone: "Africa/Johannesburg", day: "numeric", month: "long", year: "numeric",
  });
  const subject = `SelfieBox weekly AI marketing report — ${when}`;
  const intro = `Hey Stephan and Johan,`;
  const lead = meta.trigger === "cron"
    ? "Here's this Monday's automated look at the website, SEO and Google Ads."
    : "Here's the report from the analysis you just ran on the dashboard.";

  let bodyCore;
  if (parsed) {
    bodyCore = `
      <div style="margin:0 0 22px;padding:18px 20px;background:#14264d;border-radius:12px;color:#ffffff;">
        <div style="font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:#9db6e4;margin-bottom:6px;">This week's headline</div>
        <div style="font-size:15px;line-height:1.6;">${esc(parsed.summary)}</div>
      </div>
      ${parsed.quickWins?.length ? `
      <div style="margin:0 0 22px;padding:18px 20px;background:#ffffff;border:1px solid #bfe3cd;border-radius:12px;">
        <div style="font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:#1d9e57;font-weight:700;margin-bottom:8px;">Quick wins</div>
        <ul style="margin:0;padding-left:20px;font-size:13.5px;color:#33415e;">
          ${parsed.quickWins.map((w) => `<li style="margin:0 0 7px;line-height:1.5;">${esc(w)}</li>`).join("")}
        </ul>
      </div>` : ""}
      ${(parsed.sections || []).map(renderSection).join("")}`;
  } else {
    bodyCore = `<pre style="white-space:pre-wrap;font-size:12.5px;background:#ffffff;border:1px solid #e3e9f4;border-radius:12px;padding:16px;">${esc(rawText)}</pre>`;
  }

  const html = `<!doctype html><html><body style="margin:0;padding:0;background:#eef2f9;">
  <div style="max-width:660px;margin:0 auto;padding:26px 16px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
    <div style="padding:6px 4px 18px;">
      <span style="font-size:20px;font-weight:800;color:#14264d;">Selfie</span><span style="font-size:20px;font-weight:800;color:#2f73e6;">Box</span>
      <span style="font-size:12px;color:#7a869c;">&nbsp;· AI marketing report</span>
    </div>
    <div style="font-size:14px;color:#33415e;line-height:1.6;margin:0 0 18px;">
      ${esc(intro)}<br>${esc(lead)}
    </div>
    ${bodyCore}
    <div style="font-size:12px;color:#7a869c;line-height:1.6;padding:6px 4px;">
      Full report &amp; history: <a href="https://events.selfiebox.co.za" style="color:#2f73e6;">events.selfiebox.co.za</a> → Info &amp; Reporting → AI Analysis.<br>
      Generated by ${esc(meta.model || "Claude")} · ${esc(meta.periodLabel || "")} · ${meta.trigger === "cron" ? "scheduled Monday run" : "manual run"}.
    </div>
  </div></body></html>`;

  const text = [
    intro, "", lead, "",
    parsed ? `THIS WEEK'S HEADLINE\n${parsed.summary}` : rawText,
    parsed && parsed.quickWins?.length ? `\nQUICK WINS\n${parsed.quickWins.map((w) => `- ${w}`).join("\n")}` : "",
    ...(parsed ? (parsed.sections || []).map((s) => {
      const recs = (s.recommendations || []).map((r) => `- ${r.action} (${r.impact} impact, ${r.effort} effort): ${r.why}`).join("\n");
      return `\n${(SECTION_TITLES[s.key] || s.title || "").toUpperCase()} [${(HEALTH_STYLE[s.health] || HEALTH_STYLE.warn)[0]}]\n${(s.findings || []).map((f) => `- ${f}`).join("\n")}\n${recs}`;
    }) : []),
    "\nFull report: https://events.selfiebox.co.za -> Info & Reporting -> AI Analysis",
  ].filter(Boolean).join("\n");

  return { subject, html, text };
}

export async function sendAiReportEmail(meta, reportText, toOverride) {
  const to = String(toOverride || process.env.AI_REPORT_EMAIL || "").trim();
  if (!to) return { sent: false, reason: "AI_REPORT_EMAIL not set" };
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) return { sent: false, reason: "no RESEND_API_KEY" };
  const from = process.env.RESEND_FROM_EMAIL || "SelfieBox <bookings@events.selfiebox.co.za>";

  let parsed = null;
  try { parsed = JSON.parse(reportText); } catch { /* raw fallback */ }
  const { subject, html, text } = buildAiReportEmail(meta, parsed, reportText);

  const resp = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json", "User-Agent": "SelfieBox-Convex/1.0" },
    body: JSON.stringify({ from, to: [to], subject, html, text }),
  });
  const body = await resp.text();
  return { sent: resp.ok, status: resp.status, to, body: body.slice(0, 200) };
}
