import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const eventEntry = v.object({
  id: v.string(),
  text: v.string(),
  user: v.string(),
  date: v.string(),
});

const eventFile = v.object({
  id: v.string(),
  name: v.string(),
  type: v.string(),
  size: v.string(),
});

const bookingFormData = v.object({
  product: v.string(),
  customerType: v.string(),
  eventName: v.optional(v.string()),
  companyName: v.optional(v.string()),
  contactPerson: v.string(),
  cell: v.string(),
  email: v.string(),
  eventDate: v.string(),
  region: v.string(),
  address: v.string(),
  addressPlaceId: v.optional(v.string()),
  addressLat: v.optional(v.union(v.number(), v.null())),
  addressLng: v.optional(v.union(v.number(), v.null())),
  pointOfContactName: v.string(),
  pointOfContactNumber: v.string(),
  setupTime: v.optional(v.string()),
  eventStartTime: v.string(),
  eventFinishTime: v.string(),
  durationHours: v.string(),
  optionalExtras: v.array(v.string()),
  designYourself: v.string(),
  notes: v.string(),
  acceptedTerms: v.boolean(),
});

export default defineSchema({
  users: defineTable({
    clerkId: v.string(),
    email: v.string(),
    firstName: v.string(),
    surname: v.string(),
    fullName: v.string(),
    designation: v.string(),
    role: v.union(v.literal("admin"), v.literal("manager"), v.literal("user")),
    profilePic: v.optional(v.string()),
    theme: v.optional(v.union(v.literal("light"), v.literal("dark"))),
    assignedBranches: v.optional(v.array(v.string())),
    monthOrder: v.optional(v.array(v.string())),
    columnOrderAfterPayment: v.optional(v.array(v.string())),
    logisticsDayOrders: v.optional(v.record(v.string(), v.array(v.string()))),
    isApproved: v.boolean(),
    isActive: v.boolean(),
    lastSignInAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_clerk_id", ["clerkId"])
    .index("by_email", ["email"]),
  workspaces: defineTable({
    year: v.number(),
    name: v.string(),
    createdByUserId: v.optional(v.id("users")),
    createdAt: v.number(),
  }).index("by_year", ["year"]),
  events: defineTable({
    eventKey: v.string(),
    workspaceYear: v.number(),
    name: v.string(),
    eventTitle: v.optional(v.string()),
    duplicatedFromEventKey: v.optional(v.string()),
    duplicatedFromEventName: v.optional(v.string()),
    date: v.optional(v.string()),
    draftMonth: v.optional(v.string()),
    hours: v.optional(v.string()),
    branch: v.array(v.string()),
    products: v.array(v.string()),
    status: v.optional(v.string()),
    location: v.optional(v.string()),
    locationPlaceId: v.optional(v.string()),
    locationLat: v.optional(v.number()),
    locationLng: v.optional(v.number()),
    paymentStatus: v.optional(v.string()),
    accounts: v.optional(v.string()),
    quoteNumber: v.optional(v.string()),
    invoiceNumber: v.optional(v.string()),
    exVatAuto: v.optional(v.union(v.number(), v.string())),
    vinyl: v.optional(v.string()),
    gsAi: v.optional(v.string()),
    imagesSent: v.optional(v.string()),
    snappic: v.optional(v.string()),
    attendants: v.array(v.string()),
    exVat: v.optional(v.union(v.number(), v.string())),
    packageOnly: v.optional(v.string()),
    notes: v.optional(v.string()),
    customFields: v.optional(v.record(v.string(), v.union(v.string(), v.array(v.string())))),
    updates: v.array(eventEntry),
    files: v.array(eventFile),
    activity: v.array(eventEntry),
    createdByUserId: v.optional(v.id("users")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_event_key", ["eventKey"])
    .index("by_workspace_year", ["workspaceYear"])
    .index("by_date", ["date"]),
  deletedEventKeys: defineTable({
    eventKey: v.string(),
    deletedAt: v.number(),
  }).index("by_event_key", ["eventKey"]),
  labelOptions: defineTable({
    columnKey: v.string(),
    optionKey: v.string(),
    name: v.string(),
    abbreviation: v.optional(v.string()),
    branchKey: v.optional(v.string()),
    displayName: v.optional(v.string()),
    firstName: v.optional(v.string()),
    lastName: v.optional(v.string()),
    cellNumber: v.optional(v.string()),
    vehicleMake: v.optional(v.string()),
    vehicleColor: v.optional(v.string()),
    vehicleNumberPlate: v.optional(v.string()),
    email: v.optional(v.string()),
    address: v.optional(v.string()),
    addressPlaceId: v.optional(v.string()),
    addressLat: v.optional(v.union(v.number(), v.null())),
    addressLng: v.optional(v.union(v.number(), v.null())),
    color: v.string(),
    order: v.number(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_column", ["columnKey"])
    .index("by_column_option_key", ["columnKey", "optionKey"]),
  eventUpdates: defineTable({
    eventId: v.id("events"),
    body: v.string(),
    actorName: v.string(),
    legacyEntryId: v.optional(v.string()),
    createdByUserId: v.optional(v.id("users")),
    createdAt: v.number(),
  }).index("by_event", ["eventId"]),
  eventFiles: defineTable({
    eventId: v.id("events"),
    name: v.string(),
    storageId: v.optional(v.id("_storage")),
    legacyFileId: v.optional(v.string()),
    contentType: v.optional(v.string()),
    sizeLabel: v.optional(v.string()),
    createdByUserId: v.optional(v.id("users")),
    createdAt: v.number(),
  }).index("by_event", ["eventId"]),
  attendantFiles: defineTable({
    attendantId: v.id("labelOptions"),
    name: v.string(),
    fileCategory: v.string(),
    storageId: v.optional(v.id("_storage")),
    contentType: v.optional(v.string()),
    sizeLabel: v.optional(v.string()),
    createdByUserId: v.optional(v.id("users")),
    createdAt: v.number(),
  }).index("by_attendant", ["attendantId"]),
  activityLog: defineTable({
    workspaceYear: v.number(),
    eventId: v.optional(v.id("events")),
    eventName: v.optional(v.string()),
    text: v.string(),
    shortText: v.string(),
    actorName: v.string(),
    legacyEntryId: v.optional(v.string()),
    actorUserId: v.optional(v.id("users")),
    createdAt: v.number(),
    })
    .index("by_workspace_year", ["workspaceYear"])
    .index("by_event", ["eventId"]),
  eventBookings: defineTable({
      eventId: v.id("events"),
      eventKey: v.string(),
      token: v.string(),
    formData: bookingFormData,
    createdByUserId: v.optional(v.id("users")),
    submittedByUserId: v.optional(v.id("users")),
      publicAccessCount: v.number(),
      createdAt: v.number(),
      updatedAt: v.number(),
      submittedAt: v.optional(v.number()),
      lastSubmittedIp: v.optional(v.string()),
    })
      .index("by_event", ["eventId"])
      .index("by_event_key", ["eventKey"])
      .index("by_token", ["token"]),
  bookingSnapshots: defineTable({
      bookingId: v.id("eventBookings"),
      eventId: v.id("events"),
      storageId: v.id("_storage"),
      fileName: v.string(),
      sourceIp: v.optional(v.string()),
      submittedAt: v.number(),
      createdByUserId: v.optional(v.id("users")),
      createdByLabel: v.optional(v.string()),
      createdAt: v.number(),
    })
      .index("by_booking", ["bookingId"])
      .index("by_event", ["eventId"]),
  commissionSnapshots: defineTable({
      month: v.string(),
      year: v.number(),
      period: v.string(),
      attendant: v.string(),
      storageId: v.id("_storage"),
      fileName: v.string(),
      createdAt: v.number(),
      createdByUserId: v.optional(v.id("users")),
    })
      .index("by_month_attendant", ["year", "month", "attendant"]),
  commissionSummarySnapshots: defineTable({
      month: v.string(),
      year: v.number(),
      period: v.string(),
      storageId: v.id("_storage"),
      fileName: v.string(),
      createdAt: v.number(),
      createdByUserId: v.optional(v.id("users")),
    })
      .index("by_month_period", ["year", "month", "period"]),
  commissionOverrides: defineTable({
      month: v.string(),
      year: v.number(),
      attendant: v.string(),
      eventId: v.string(),
      hoursPayable: v.optional(v.string()),
      amount: v.optional(v.string()),
      car: v.optional(v.string()),
      km: v.optional(v.string()),
      note: v.optional(v.string()),
      updatedAt: v.number(),
      updatedByUserId: v.optional(v.id("users")),
    })
      .index("by_month_attendant", ["year", "month", "attendant"])
      .index("by_month_attendant_event", ["year", "month", "attendant", "eventId"]),
  commissionRates: defineTable({
      singletonKey: v.string(),
      twoHours: v.number(),
      threeHours: v.number(),
      fourHours: v.number(),
      fiveHours: v.number(),
      sixPlusHours: v.number(),
      perKmRate: v.number(),
      updatedAt: v.number(),
      updatedByUserId: v.optional(v.id("users")),
    })
      .index("by_singleton_key", ["singletonKey"]),
  turnoverNoEventsOverrides: defineTable({
      regionKey: v.string(),
      year: v.number(),
      noEvents: v.number(),
      updatedAt: v.number(),
      updatedByUserId: v.optional(v.id("users")),
    })
      .index("by_region_year", ["regionKey", "year"]),
  columnPermissions: defineTable({
    columnKey: v.string(),
    subjectType: v.union(v.literal("role"), v.literal("user")),
    role: v.optional(v.union(v.literal("admin"), v.literal("manager"), v.literal("user"))),
    userId: v.optional(v.id("users")),
    canView: v.boolean(),
    canEdit: v.boolean(),
    updatedAt: v.number(),
  })
    .index("by_column", ["columnKey"])
    .index("by_column_role", ["columnKey", "role"])
    .index("by_column_user", ["columnKey", "userId"]),
  customColumns: defineTable({
    columnKey: v.string(),
    label: v.string(),
    type: v.union(
      v.literal("text"),
      v.literal("number"),
      v.literal("date"),
      v.literal("singleItem"),
      v.literal("multiItem"),
    ),
    order: v.number(),
    isActive: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_column_key", ["columnKey"])
    .index("by_order", ["order"]),
  staticColumnLabels: defineTable({
    columnKey: v.string(),
    label: v.string(),
    updatedAt: v.number(),
  }).index("by_column_key", ["columnKey"]),
});
