export const STATUS_STYLES = {
  'Event Completed': { background: '#23b26d', color: '#ffffff' },
  'In Progress': { background: '#f1a53a', color: '#ffffff' },
  'Quote Sent': { background: '#2358c8', color: '#ffffff' },
  Cancelled: { background: '#d83d57', color: '#ffffff' },
  Postponed: { background: '#b5b82d', color: '#ffffff' },
  Refunded: { background: '#7d4ad8', color: '#ffffff' },
  Rejected: { background: '#f11f8c', color: '#ffffff' },
  'No response': { background: '#ab8ee5', color: '#ffffff' },
  'Multi Day': { background: '#8ac63f', color: '#ffffff' },
};

export const PAYMENT_STYLES = {
  '100%': { background: '#2b61d1', color: '#ffffff' },
  '50%': { background: '#6ec5f0', color: '#ffffff' },
  PO: { background: '#b49ae6', color: '#ffffff' },
  'Invoiced, 0%': { background: '#df3652', color: '#ffffff' },
  Pending: { background: '#b7b7b7', color: '#ffffff' },
};

export const YES_NO_STYLES = {
  Yes: { background: '#2fc26d', color: '#ffffff' },
  No: { background: '#d93c56', color: '#ffffff' },
  Pending: { background: '#bcbcbc', color: '#ffffff' },
  Ready: { background: '#98c8ff', color: '#0f2442' },
};

export const BRANCH_STYLES = {
  CT: { background: '#d7e5f5', color: '#315370' },
  GP: { background: '#c8ddf7', color: '#28486f' },
  DBN: { background: '#dbeed6', color: '#31692f' },
  PE: { background: '#f7e3c5', color: '#734a19' },
};

export const PRODUCT_STYLES = {
  '360° Orbit': { background: '#d9edf8', color: '#2c5672' },
  'HB White': { background: '#e7edf6', color: '#3d546d' },
  Nano: { background: '#d9e4f3', color: '#36526d' },
  'Retro Pod': { background: '#efe4c7', color: '#6f5423' },
  Retro: { background: '#e8dccb', color: '#6e5437' },
  'Mirror Booth': { background: '#dddff4', color: '#494f7a' },
  '360° Curve': { background: '#e7f2ff', color: '#35598d' },
  Mosaic: { background: '#d3eef3', color: '#2b626d' },
  Printer: { background: '#efe2dc', color: '#7a5147' },
  TV: { background: '#d7e6d2', color: '#44653a' },
};

export const BOARD_COLUMNS = [
  { key: 'name', label: 'Name / Item' },
  { key: 'date', label: 'Date' },
  { key: 'hours', label: 'Hours' },
  { key: 'branch', label: 'Branch' },
  { key: 'products', label: 'Product/s' },
  { key: 'status', label: 'Status' },
  { key: 'location', label: 'Location' },
  { key: 'paymentStatus', label: 'Payment' },
  { key: 'vinyl', label: 'Vinyl?' },
  { key: 'gsAi', label: 'GS / AI?' },
  { key: 'imagesSent', label: 'Images sent?' },
  { key: 'snappic', label: 'Snappic?' },
  { key: 'attendants', label: 'Attendant/s' },
  { key: 'exVat', label: 'Ex. VAT' },
  { key: 'packageOnly', label: 'Package only' },
];

export const STATUS_OPTIONS = Object.keys(STATUS_STYLES);
export const PAYMENT_OPTIONS = ['100%', '50%', 'PO', 'Invoiced, 0%', 'Pending'];
export const BRANCH_OPTIONS = ['CT', 'GP', 'DBN', 'PE'];
export const PRODUCT_OPTIONS = ['360° Orbit', 'HB White', 'Nano', 'Retro Pod', 'Retro', 'Mirror Booth', '360° Curve', 'Mosaic', 'Printer', 'TV'];

export const seedEvents = [
  {
    id: 'evt-001',
    name: 'Full Circle Agency',
    date: '2026-03-03',
    hours: '17:00-00:00',
    branch: ['GP'],
    products: ['360° Orbit'],
    status: 'Event Completed',
    location: 'Inimitable Wedding Venue, Riverside Road, Zwartkops, Muldersdrift, South Africa',
    paymentStatus: '100%',
    vinyl: 'No',
    gsAi: 'No',
    imagesSent: 'Pending',
    snappic: 'Ready',
    attendants: ['Tshepo'],
    exVat: 8770,
    packageOnly: '',
    notes: 'Signed off and completed without issues.',
    files: [
      { id: 'f-001', name: 'SelfieBox_GP_FullCircle_Quote.pdf', type: 'Quote', size: '1.4 MB' },
      { id: 'f-002', name: 'PaymentConfirmation.pdf', type: 'Payment', size: '420 KB' }
    ],
    activity: [
      { id: 'a-001', text: 'Booking marked as completed.', date: '2026-03-03 23:48', user: 'Nalini' },
      { id: 'a-002', text: 'Payment captured at 100%.', date: '2026-03-01 10:12', user: 'Finance' }
    ]
  },
  {
    id: 'evt-002',
    name: 'Phoenix ICE Solutions (Set up by 07h30)',
    date: '2026-03-03',
    hours: '08:00-10:00',
    branch: ['GP'],
    products: ['HB White'],
    status: 'Event Completed',
    location: '135 Rivonia Road, Sandown, Sandton, South Africa',
    paymentStatus: 'Pending',
    vinyl: 'No',
    gsAi: 'No',
    imagesSent: 'Pending',
    snappic: 'Ready',
    attendants: [],
    exVat: 3640,
    packageOnly: '',
    notes: 'Morning corporate activation with early setup requirement.',
    files: [{ id: 'f-003', name: 'PhoenixICE_CallSheet.pdf', type: 'Call Sheet', size: '310 KB' }],
    activity: [{ id: 'a-003', text: 'Crew checklist approved.', date: '2026-03-02 16:08', user: 'Ops' }]
  },
  {
    id: 'evt-003',
    name: 'Kaii Brand',
    date: '2026-03-04',
    hours: '08:00 - 13:00',
    branch: ['CT'],
    products: ['HB White'],
    status: 'Event Completed',
    location: 'Devon Valley Primary School, Devon Valley Road, Devonvallei, Stellenbosch, South Africa',
    paymentStatus: 'Pending',
    vinyl: 'Yes',
    gsAi: 'No',
    imagesSent: 'Ready',
    snappic: 'Ready',
    attendants: ['Burton', 'Caleb'],
    exVat: 18200,
    packageOnly: '',
    notes: 'School activation with branded vinyl package.',
    files: [{ id: 'f-004', name: 'KaiiBrand_Brief.docx', type: 'Brief', size: '220 KB' }],
    activity: [{ id: 'a-004', text: 'Vinyl artwork approved.', date: '2026-03-02 09:45', user: 'Studio' }]
  },
  {
    id: 'evt-004',
    name: 'Dreams Agency',
    date: '2026-03-04',
    hours: '18:00 - 21:00',
    branch: ['CT'],
    products: ['Nano'],
    status: 'Event Completed',
    location: 'Cape Town, South Africa',
    paymentStatus: '100%',
    vinyl: 'Yes',
    gsAi: 'No',
    imagesSent: 'Ready',
    snappic: 'Ready',
    attendants: ['KB'],
    exVat: 5740,
    packageOnly: '',
    notes: 'Compact setup for an agency event in Cape Town.',
    files: [{ id: 'f-005', name: 'DreamsAgency_Invoice.pdf', type: 'Invoice', size: '510 KB' }],
    activity: [{ id: 'a-005', text: 'Invoice settled in full.', date: '2026-03-04 14:40', user: 'Finance' }]
  },
  {
    id: 'evt-005',
    name: 'BlackPeppa Experiences (6-8 March)',
    date: '2026-03-06',
    hours: '09:00 - 18:00',
    branch: ['CT'],
    products: ['Retro Pod'],
    status: 'Multi Day',
    location: 'Cape Town International Airport (CPT), Matroosfontein, Cape Town, South Africa',
    paymentStatus: '100%',
    vinyl: 'No',
    gsAi: 'No',
    imagesSent: 'Pending',
    snappic: 'Ready',
    attendants: ['KB', 'Roland'],
    exVat: 24500,
    packageOnly: '',
    notes: 'Three-day airport activation. Needs staggered staffing and daily checks.',
    files: [
      { id: 'f-006', name: 'BlackPeppa_RunSheet.pdf', type: 'Run Sheet', size: '780 KB' },
      { id: 'f-007', name: 'AirportPermit.pdf', type: 'Permit', size: '640 KB' }
    ],
    activity: [
      { id: 'a-006', text: 'Multi-day logistics locked in.', date: '2026-03-05 15:30', user: 'Ops' },
      { id: 'a-007', text: 'Retro Pod assigned to Cape Town stock.', date: '2026-03-05 09:10', user: 'Warehouse' }
    ]
  },
  {
    id: 'evt-006',
    name: 'GC Consulting // Chantall le Roux',
    date: '2026-03-07',
    hours: '16:00-18:00',
    branch: ['GP'],
    products: ['Nano'],
    status: 'Event Completed',
    location: 'La Perna Diner, 780 Breed Street, Montana, Pretoria, South Africa',
    paymentStatus: '100%',
    vinyl: 'No',
    gsAi: 'No',
    imagesSent: 'Pending',
    snappic: 'Ready',
    attendants: ['Tshepo'],
    exVat: 3640,
    packageOnly: '',
    notes: 'Short private event with quick turnaround.',
    files: [{ id: 'f-008', name: 'GCConsulting_DeliveryNote.pdf', type: 'Delivery', size: '240 KB' }],
    activity: [{ id: 'a-008', text: 'Booking closed after event.', date: '2026-03-07 19:12', user: 'Nalini' }]
  },
  {
    id: 'evt-007',
    name: 'Lens Art',
    date: '2026-03-07',
    hours: '16:00-23:00',
    branch: ['GP'],
    products: ['360° Orbit', 'HB White'],
    status: 'In Progress',
    location: 'Colosseum Reale, Roodeplaat, South Africa',
    paymentStatus: '100%',
    vinyl: 'No',
    gsAi: 'No',
    imagesSent: 'Ready',
    snappic: 'Ready',
    attendants: ['Sibusiso', 'Ntokozo'],
    exVat: 15400,
    packageOnly: '',
    notes: 'Dual-product booking. Final wrap-up assets still pending.',
    files: [
      { id: 'f-009', name: 'LensArt_Staffing.xlsx', type: 'Staffing', size: '95 KB' },
      { id: 'f-010', name: 'LensArt_PaymentProof.pdf', type: 'Payment', size: '560 KB' }
    ],
    activity: [{ id: 'a-009', text: 'Post-event media still waiting from crew.', date: '2026-03-08 08:30', user: 'Ops' }]
  },
  {
    id: 'evt-008',
    name: 'University of Pretoria (UP)(DC)',
    date: '2026-03-07',
    hours: '09:00-13:00',
    branch: ['GP'],
    products: ['Nano'],
    status: 'Event Completed',
    location: 'University of Pretoria, Lynnwood Road, Hatfield, Pretoria, South Africa',
    paymentStatus: 'Pending',
    vinyl: 'No',
    gsAi: 'No',
    imagesSent: 'Pending',
    snappic: 'Ready',
    attendants: ['Tshepo'],
    exVat: 5700,
    packageOnly: '',
    notes: 'Campus day booking with standard setup.',
    files: [{ id: 'f-011', name: 'UP_CallSheet.pdf', type: 'Call Sheet', size: '260 KB' }],
    activity: [{ id: 'a-010', text: 'Awaiting payment allocation.', date: '2026-03-06 11:54', user: 'Finance' }]
  },
  {
    id: 'evt-009',
    name: 'TOYOTA',
    date: '2026-03-12',
    hours: '10:00 - 14:00',
    branch: ['CT'],
    products: ['360° Orbit'],
    status: 'Quote Sent',
    location: 'Killarney International Raceway, Potsdam Road, Table View, Cape Town, South Africa',
    paymentStatus: '50%',
    vinyl: 'No',
    gsAi: 'No',
    imagesSent: 'Pending',
    snappic: 'Pending',
    attendants: ['Gaby'],
    exVat: 9200,
    packageOnly: '',
    notes: 'Large-format activation in quoting phase with deposit received.',
    files: [{ id: 'f-012', name: 'Toyota_Quote_v2.pdf', type: 'Quote', size: '690 KB' }],
    activity: [{ id: 'a-011', text: 'Quote shared with client.', date: '2026-03-10 13:22', user: 'Sales' }]
  },
  {
    id: 'evt-010',
    name: 'Media24',
    date: '2026-03-20',
    hours: '13:00 - 23:00',
    branch: ['GP'],
    products: ['Mirror Booth'],
    status: 'Postponed',
    location: 'Sandton Convention Centre, Maude Street, Sandown, Sandton, South Africa',
    paymentStatus: 'PO',
    vinyl: 'Yes',
    gsAi: 'No',
    imagesSent: 'Pending',
    snappic: 'Pending',
    attendants: ['Tshepo Mosia'],
    exVat: 11800,
    packageOnly: '',
    notes: 'Postponed to await venue confirmation. Purchase order already issued.',
    files: [{ id: 'f-013', name: 'Media24_PO.pdf', type: 'PO', size: '330 KB' }],
    activity: [{ id: 'a-012', text: 'Date held while venue reconfirms.', date: '2026-03-18 17:04', user: 'Nalini' }]
  },
  {
    id: 'evt-011',
    name: 'Athandiwe Saba (Magnets+GIFs)',
    date: '2026-03-23',
    hours: '15:00-18:00',
    branch: ['GP'],
    products: ['Retro'],
    status: 'Cancelled',
    location: '213 Frances Street, Observatory, Johannesburg, South Africa',
    paymentStatus: 'Invoiced, 0%',
    vinyl: 'No',
    gsAi: 'Yes',
    imagesSent: 'Pending',
    snappic: 'Pending',
    attendants: ['Dumisani'],
    exVat: 6400,
    packageOnly: '',
    notes: 'Cancelled after invoice issued. Needs follow-up on cancellation fees.',
    files: [{ id: 'f-014', name: 'CancellationNotice.pdf', type: 'Notice', size: '180 KB' }],
    activity: [{ id: 'a-013', text: 'Client cancelled after invoicing.', date: '2026-03-21 08:16', user: 'Sales' }]
  },
  {
    id: 'evt-012',
    name: 'Open Gallery',
    date: '2026-03-25',
    hours: '18:00-23:30',
    branch: ['GP', 'CT'],
    products: ['Mosaic', 'Printer', 'TV'],
    status: 'No response',
    location: 'Lyric Theatre, Data Crescent, Ormonde, Johannesburg South, South Africa',
    paymentStatus: 'Pending',
    vinyl: 'Yes',
    gsAi: 'Yes',
    imagesSent: 'Pending',
    snappic: 'Pending',
    attendants: ['Lee-Ann', 'Khazimla'],
    exVat: 31200,
    packageOnly: 18000,
    notes: 'Complex multi-output installation. Client approval is still outstanding.',
    files: [
      { id: 'f-015', name: 'OpenGallery_RenderBoard.pdf', type: 'Creative', size: '2.1 MB' },
      { id: 'f-016', name: 'OpenGallery_Mockups.zip', type: 'Assets', size: '8.4 MB' }
    ],
    activity: [
      { id: 'a-014', text: 'Follow-up reminder sent to client.', date: '2026-03-24 15:12', user: 'Nalini' },
      { id: 'a-015', text: 'Cross-branch staffing proposed.', date: '2026-03-23 09:05', user: 'Ops' }
    ]
  }
];
